#!/bin/bash

# ==============================================================================
# HyperInit - System Module
# ==============================================================================

system_menu() {
    show_menu "SYSTEM INITIALIZATION" \
        "1. Change Mirrors (LinuxMirrors.cn)" \
        "2. Update System Packages" \
        "3. Configure SSH (Disable Root Login)" \
        "4. Enable UFW Firewall" \
        "5. Repair APT Sources (Fix broken docker.list / Microsoft keys)" \
        "6. Install Fail2ban (Brute-force protection)" \
        "7. Install Unattended Upgrades (Auto security updates, Debian/Ubuntu)" \
        "8. Install Timeshift (System snapshots & restore)" \
        "B. Back to Main Menu"

    case "$SELECTION" in
        *"Change Mirrors"*)
            change_mirrors
            ;;
        *"Update System"*)
            update_system
            ;;
        *"Configure SSH"*)
            harden_ssh
            ;;
        *"Enable UFW"*)
            enable_firewall
            ;;
        *"Repair APT"*)
            repair_apt_sources
            ;;
        *"Fail2ban"*)
            install_fail2ban
            ;;
        *"Unattended Upgrades"*)
            install_unattended_upgrades
            ;;
        *"Timeshift"*)
            install_timeshift
            ;;
        *"Back"*)
            return
            ;;
    esac
    read -n 1 -s -r -p "Press any key to continue..."
    # Recursively show menu again
    system_menu
}

change_mirrors() {
    info "Configuring System Mirrors..."
    
    # Only support Debian/Ubuntu for now
    if [ "$PKG_MANAGER" != "apt" ]; then
        warn "Mirror configuration currently only supports Debian/Ubuntu systems."
        echo ""
        info "For other distributions:"
        echo -e "  ${NEON_CYAN}•${RESET} Fedora/RHEL: Edit /etc/yum.repos.d/"
        echo -e "  ${NEON_CYAN}•${RESET} Arch: Edit /etc/pacman.d/mirrorlist"
        echo ""
        read -n 1 -s -r -p "Press any key to continue..."
        return
    fi
    
    # Detect Debian or Ubuntu
    local distro=""
    local codename=""
    
    if [ -f /etc/os-release ]; then
        . /etc/os-release
        distro=$ID
        codename=$VERSION_CODENAME
    fi
    
    # Show mirror selection menu
    echo ""
    echo -e "${NEON_CYAN}Select Mirror Source:${RESET}"
    echo "  1. Tsinghua University (清华大学)"
    echo "  2. USTC (中国科学技术大学)"
    echo "  3. Aliyun (阿里云)"
    echo "  4. Tencent Cloud (腾讯云)"
    echo "  5. Huawei Cloud (华为云)"
    echo "  6. Official (Keep current/official)"
    echo ""
    read -p "Enter your choice [1-6]: " mirror_choice
    
    local mirror_url=""
    case "$mirror_choice" in
        1) mirror_url="https://mirrors.tuna.tsinghua.edu.cn" ;;
        2) mirror_url="https://mirrors.ustc.edu.cn" ;;
        3) mirror_url="https://mirrors.aliyun.com" ;;
        4) mirror_url="https://mirrors.tencent.com" ;;
        5) mirror_url="https://mirrors.huaweicloud.com" ;;
        6) 
            info "Keeping current mirror configuration."
            read -n 1 -s -r -p "Press any key to continue..."
            return
            ;;
        *)
            error "Invalid choice. Aborting."
            read -n 1 -s -r -p "Press any key to continue..."
            return
            ;;
    esac
    
    info "Selected mirror: $mirror_url"
    
    # Backup existing sources
    if [ -f /etc/apt/sources.list ]; then
        sudo cp /etc/apt/sources.list /etc/apt/sources.list.bak.$(date +%Y%m%d_%H%M%S)
        success "Backed up /etc/apt/sources.list"
    fi
    
    if [ -f /etc/apt/sources.list.d/debian.sources ]; then
        sudo cp /etc/apt/sources.list.d/debian.sources /etc/apt/sources.list.d/debian.sources.bak.$(date +%Y%m%d_%H%M%S)
        success "Backed up debian.sources"
    fi
    
    if [ -f /etc/apt/sources.list.d/ubuntu.sources ]; then
        sudo cp /etc/apt/sources.list.d/ubuntu.sources /etc/apt/sources.list.d/ubuntu.sources.bak.$(date +%Y%m%d_%H%M%S)
        success "Backed up ubuntu.sources"
    fi
    
    # Generate new sources based on distro
    if [ "$distro" = "debian" ]; then
        info "Configuring Debian $codename sources..."
        sudo tee /etc/apt/sources.list > /dev/null <<EOF
# Generated by HyperInit
deb $mirror_url/debian/ $codename main contrib non-free non-free-firmware
deb $mirror_url/debian/ $codename-updates main contrib non-free non-free-firmware
deb $mirror_url/debian/ $codename-backports main contrib non-free non-free-firmware
deb $mirror_url/debian-security $codename-security main contrib non-free non-free-firmware
EOF
    elif [ "$distro" = "ubuntu" ]; then
        info "Configuring Ubuntu $codename sources..."
        sudo tee /etc/apt/sources.list > /dev/null <<EOF
# Generated by HyperInit
deb $mirror_url/ubuntu/ $codename main restricted universe multiverse
deb $mirror_url/ubuntu/ $codename-updates main restricted universe multiverse
deb $mirror_url/ubuntu/ $codename-backports main restricted universe multiverse
deb $mirror_url/ubuntu/ $codename-security main restricted universe multiverse
EOF
    else
        warn "Unsupported distribution: $distro"
        read -n 1 -s -r -p "Press any key to continue..."
        return
    fi
    
    success "Mirror configuration updated."
    
    # Update package index
    run_task "Updating package index" sudo apt update
    
    success "Mirror switching complete."
    read -n 1 -s -r -p "Press any key to continue..."
}

update_system() {
    info "This will update all system packages."
    echo ""
    read -p "Continue? [Y/n] " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]] && [[ -n $REPLY ]]; then
        info "Update cancelled."
        read -n 1 -s -r -p "Press any key to continue..."
        return
    fi
    
    case "$PKG_MANAGER" in
        apt)
            run_task "Updating package lists" sudo apt-get update
            run_task "Upgrading packages" sudo apt-get upgrade -y
            ;;
        dnf)
            run_task "Updating system" sudo dnf update -y
            ;;
        pacman)
            run_task "Updating system" sudo pacman -Syu --noconfirm
            ;;
    esac
    success "System updated."
    read -n 1 -s -r -p "Press any key to continue..."
}

harden_ssh() {
    info "Hardening SSH configuration..."
    if [ -f /etc/ssh/sshd_config ]; then
        # Back up first
        sudo cp /etc/ssh/sshd_config /etc/ssh/sshd_config.bak
        
        # Disable Root Login
        sudo sed -i 's/^#PermitRootLogin.*/PermitRootLogin no/' /etc/ssh/sshd_config
        sudo sed -i 's/^PermitRootLogin.*/PermitRootLogin no/' /etc/ssh/sshd_config
        
        # Disable Password Auth (Optional, usually risky if no keys set up, skipping for safety or ask user)
        # For now, just Root Login
        
        run_task "Restarting SSH Service" sudo systemctl restart sshd
        success "SSH hardened: Root login disabled."
    else
        warn "/etc/ssh/sshd_config not found."
    fi
    sleep 2
}

enable_firewall() {
    info "Enabling UFW Firewall..."
    install_pkg "ufw"

    run_task "Allowing SSH" sudo ufw allow ssh
    run_task "Enabling UFW" sudo ufw --force enable
    success "Firewall enabled."
    sleep 2
}

# Repair broken APT sources (malformed docker.list, conflicting Microsoft Signed-By).
# Call this when apt-get update fails with "Malformed entry" or "Conflicting values set for option Signed-By".
# Usage: repair_apt_sources [--quiet]  (--quiet skips "Press any key" prompts, for use from other modules)
repair_apt_sources() {
    local quiet=
    [ "$1" = "--quiet" ] && quiet=1

    if [ "$PKG_MANAGER" != "apt" ]; then
        warn "Repair APT sources only applies to Debian/Ubuntu (apt)."
        [ -z "$quiet" ] && read -n 1 -s -r -p "Press any key to continue..."
        return
    fi

    info "Checking APT sources..."
    local update_out
    update_out=$(sudo apt-get update 2>&1)
    local update_rc=$?
    if [ $update_rc -eq 0 ]; then
        success "APT sources are OK. No repair needed."
        [ -z "$quiet" ] && read -n 1 -s -r -p "Press any key to continue..."
        return
    fi

    info "APT update failed. Attempting automatic repair..."
    local repaired=0

    # Fix malformed docker.list (common: wrong format or empty component)
    if echo "$update_out" | grep -q "docker.list.*Malformed\|Malformed.*docker.list"; then
        if [ -f /etc/apt/sources.list.d/docker.list ]; then
            sudo cp /etc/apt/sources.list.d/docker.list "/etc/apt/sources.list.d/docker.list.bak.$(date +%Y%m%d_%H%M%S)"
            sudo rm -f /etc/apt/sources.list.d/docker.list
            success "Backed up and removed malformed /etc/apt/sources.list.d/docker.list (re-add Docker from Dev menu if needed)."
            repaired=1
        fi
    fi

    # Fix conflicting Microsoft Signed-By: use single key path /etc/apt/keyrings/packages.microsoft.gpg
    local need_key=
    if echo "$update_out" | grep -q "Signed-By.*microsoft\|packages.microsoft.com.*Signed-By\|Conflicting values set for option Signed-By"; then
        need_key=1
    fi
    local f
    for f in /etc/apt/sources.list.d/*.list /etc/apt/sources.list.d/*.sources; do
        [ -f "$f" ] || continue
        grep -q "packages.microsoft.com" "$f" 2>/dev/null || continue
        if grep -q "/usr/share/keyrings/microsoft.gpg" "$f" 2>/dev/null; then
            sudo sed -i 's|signed-by=/usr/share/keyrings/microsoft.gpg|signed-by=/etc/apt/keyrings/packages.microsoft.gpg|g' "$f"
            need_key=1
            success "Updated $(basename "$f") to use Signed-By=/etc/apt/keyrings/packages.microsoft.gpg"
            repaired=1
        elif ! grep -q "signed-by=" "$f" 2>/dev/null; then
            # e.g. old microsoft-edge.list has no signed-by → add it to avoid conflict with vscode.list
            sudo sed -i 's/\[arch=\([^]]*\)\]/[arch=\1 signed-by=\/etc\/apt\/keyrings\/packages.microsoft.gpg]/' "$f"
            need_key=1
            success "Added Signed-By to $(basename "$f") for packages.microsoft.com"
            repaired=1
        fi
    done
    if [ -n "$need_key" ] && [ ! -f /etc/apt/keyrings/packages.microsoft.gpg ]; then
        if [ -f /usr/share/keyrings/microsoft.gpg ]; then
            sudo install -D -o root -g root -m 644 /usr/share/keyrings/microsoft.gpg /etc/apt/keyrings/packages.microsoft.gpg
        elif [ -f /etc/apt/trusted.gpg.d/microsoft-edge.gpg ]; then
            sudo install -D -o root -g root -m 644 /etc/apt/trusted.gpg.d/microsoft-edge.gpg /etc/apt/keyrings/packages.microsoft.gpg
        fi
    fi

    if [ $repaired -eq 1 ]; then
        run_task "Re-running apt-get update" sudo apt-get update
    fi

    update_out=$(sudo apt-get update 2>&1)
    if [ $? -ne 0 ]; then
        error "APT sources could not be fully repaired. Please fix manually:"
        echo -e "  ${NEON_CYAN}•${RESET} Malformed docker.list: sudo rm /etc/apt/sources.list.d/docker.list (or fix the line format)"
        echo -e "  ${NEON_CYAN}•${RESET} Microsoft conflict: ensure all sources under /etc/apt/sources.list.d/ use the same Signed-By path for packages.microsoft.com"
        echo ""
        echo "$update_out"
    else
        success "APT sources repaired successfully."
    fi
    [ -z "$quiet" ] && read -n 1 -s -r -p "Press any key to continue..."
}

install_fail2ban() {
    info "Installing Fail2ban (brute-force protection for SSH and other services)..."

    install_pkg "fail2ban" || return 1

    if command -v systemctl &>/dev/null; then
        run_task "Enabling Fail2ban" sudo systemctl enable fail2ban
        run_task "Starting Fail2ban" sudo systemctl start fail2ban
    fi

    success "Fail2ban installed."
    info "Config: /etc/fail2ban/jail.local (copy from jail.conf). Default SSH jail is usually enabled."
}

install_unattended_upgrades() {
    info "Installing Unattended Upgrades (automatic security updates)..."

    if [ "$PKG_MANAGER" != "apt" ]; then
        warn "Unattended-upgrades is only available on Debian/Ubuntu (apt)."
        read -n 1 -s -r -p "Press any key to continue..."
        return
    fi

    install_pkg "unattended-upgrades" || return 1
    install_pkg "apt-listchanges" || true

    run_task "Enabling automatic updates" sudo dpkg-reconfigure -plow unattended-upgrades

    success "Unattended-upgrades installed."
    info "Config: /etc/apt/apt.conf.d/50unattended-upgrades and /etc/apt/apt.conf.d/20auto-upgrades."
}

install_timeshift() {
    info "Installing Timeshift (system snapshots and restore, useful for desktop)..."

    local pkg=""
    case "$PKG_MANAGER" in
        apt)
            pkg="timeshift"
            ;;
        dnf)
            pkg="timeshift"
            ;;
        pacman)
            pkg="timeshift"
            ;;
        *)
            warn "Timeshift installation currently supports apt, dnf, and pacman only."
            return 1
            ;;
    esac

    install_pkg "$pkg" || return 1

    success "Timeshift installed."
    info "Run 'timeshift' or 'timeshift-gtk' to create and manage snapshots."
}
