#!/bin/bash

# ==============================================================================
# HyperInit - System Module
# ==============================================================================

system_menu() {
    show_menu "SYSTEM INITIALIZATION" \
        "1. Change Mirrors (LinuxMirrors.cn)" \
        "2. Update System Packages" \
        "3. Configure SSH (Disable Root Login)" \
        "4. Enable UFW Firewall" \
        "B. Back to Main Menu"

    case "$SELECTION" in
        *"Change Mirrors"*)
            change_mirrors
            ;;
        *"Update System"*)
            update_system
            ;;
        *"Configure SSH"*)
            harden_ssh
            ;;
        *"Enable UFW"*)
            enable_firewall
            ;;
        *"Back"*)
            return
            ;;
    esac
    # Recursively show menu again
    system_menu
}

change_mirrors() {
    info "Configuring System Mirrors..."
    
    # Only support Debian/Ubuntu for now
    if [ "$PKG_MANAGER" != "apt" ]; then
        warn "Mirror configuration currently only supports Debian/Ubuntu systems."
        warn "For other systems, please configure manually."
        read -n 1 -s -r -p "Press any key to continue..."
        return
    fi
    
    # Detect Debian or Ubuntu
    local distro=""
    local codename=""
    
    if [ -f /etc/os-release ]; then
        . /etc/os-release
        distro=$ID
        codename=$VERSION_CODENAME
    fi
    
    # Show mirror selection menu
    echo ""
    echo -e "${NEON_CYAN}Select Mirror Source:${RESET}"
    echo "  1. Tsinghua University (清华大学)"
    echo "  2. USTC (中国科学技术大学)"
    echo "  3. Aliyun (阿里云)"
    echo "  4. Tencent Cloud (腾讯云)"
    echo "  5. Huawei Cloud (华为云)"
    echo "  6. Official (Keep current/official)"
    echo ""
    read -p "Enter your choice [1-6]: " mirror_choice
    
    local mirror_url=""
    case "$mirror_choice" in
        1) mirror_url="https://mirrors.tuna.tsinghua.edu.cn" ;;
        2) mirror_url="https://mirrors.ustc.edu.cn" ;;
        3) mirror_url="https://mirrors.aliyun.com" ;;
        4) mirror_url="https://mirrors.tencent.com" ;;
        5) mirror_url="https://mirrors.huaweicloud.com" ;;
        6) 
            info "Keeping current mirror configuration."
            read -n 1 -s -r -p "Press any key to continue..."
            return
            ;;
        *)
            error "Invalid choice. Aborting."
            read -n 1 -s -r -p "Press any key to continue..."
            return
            ;;
    esac
    
    info "Selected mirror: $mirror_url"
    
    # Backup existing sources
    if [ -f /etc/apt/sources.list ]; then
        sudo cp /etc/apt/sources.list /etc/apt/sources.list.bak.$(date +%Y%m%d_%H%M%S)
        success "Backed up /etc/apt/sources.list"
    fi
    
    if [ -f /etc/apt/sources.list.d/debian.sources ]; then
        sudo cp /etc/apt/sources.list.d/debian.sources /etc/apt/sources.list.d/debian.sources.bak.$(date +%Y%m%d_%H%M%S)
        success "Backed up debian.sources"
    fi
    
    if [ -f /etc/apt/sources.list.d/ubuntu.sources ]; then
        sudo cp /etc/apt/sources.list.d/ubuntu.sources /etc/apt/sources.list.d/ubuntu.sources.bak.$(date +%Y%m%d_%H%M%S)
        success "Backed up ubuntu.sources"
    fi
    
    # Generate new sources based on distro
    if [ "$distro" = "debian" ]; then
        info "Configuring Debian $codename sources..."
        sudo tee /etc/apt/sources.list > /dev/null <<EOF
# Generated by HyperInit
deb $mirror_url/debian/ $codename main contrib non-free non-free-firmware
deb $mirror_url/debian/ $codename-updates main contrib non-free non-free-firmware
deb $mirror_url/debian/ $codename-backports main contrib non-free non-free-firmware
deb $mirror_url/debian-security $codename-security main contrib non-free non-free-firmware
EOF
    elif [ "$distro" = "ubuntu" ]; then
        info "Configuring Ubuntu $codename sources..."
        sudo tee /etc/apt/sources.list > /dev/null <<EOF
# Generated by HyperInit
deb $mirror_url/ubuntu/ $codename main restricted universe multiverse
deb $mirror_url/ubuntu/ $codename-updates main restricted universe multiverse
deb $mirror_url/ubuntu/ $codename-backports main restricted universe multiverse
deb $mirror_url/ubuntu/ $codename-security main restricted universe multiverse
EOF
    else
        warn "Unsupported distribution: $distro"
        read -n 1 -s -r -p "Press any key to continue..."
        return
    fi
    
    success "Mirror configuration updated."
    
    # Update package index
    run_task "Updating package index" sudo apt update
    
    success "Mirror switching complete."
    read -n 1 -s -r -p "Press any key to continue..."
}

update_system() {
    info "Updating system packages..."
    case "$PKG_MANAGER" in
        apt)
            run_task "Updating package lists" sudo apt-get update
            run_task "Upgrading packages" sudo apt-get upgrade -y
            ;;
        dnf)
            run_task "Updating system" sudo dnf update -y
            ;;
        pacman)
            run_task "Updating system" sudo pacman -Syu --noconfirm
            ;;
    esac
}

harden_ssh() {
    info "Hardening SSH configuration..."
    if [ -f /etc/ssh/sshd_config ]; then
        # Back up first
        sudo cp /etc/ssh/sshd_config /etc/ssh/sshd_config.bak
        
        # Disable Root Login
        sudo sed -i 's/^#PermitRootLogin.*/PermitRootLogin no/' /etc/ssh/sshd_config
        sudo sed -i 's/^PermitRootLogin.*/PermitRootLogin no/' /etc/ssh/sshd_config
        
        # Disable Password Auth (Optional, usually risky if no keys set up, skipping for safety or ask user)
        # For now, just Root Login
        
        run_task "Restarting SSH Service" sudo systemctl restart sshd
        success "SSH hardened: Root login disabled."
    else
        warn "/etc/ssh/sshd_config not found."
    fi
    sleep 2
}

enable_firewall() {
    info "Enabling UFW Firewall..."
    install_pkg "ufw"
    
    run_task "Allowing SSH" sudo ufw allow ssh
    run_task "Enabling UFW" sudo ufw --force enable
    success "Firewall enabled."
    sleep 2
}
